#!/usr/bin/env bash
#
# Foundry · one-time VM setup for the ingestion worker. Runs AS ROOT on
# foundry-worker, mirrors infra/vm/bootstrap.sh's structure closely so the
# two never drift in the pieces they DO share — but this VM has no public
# listener at all, so everything gateway-specific (nginx, the Cloudflare
# origin cert, gateway.env's upload-ticket secrets) is absent on purpose.
#
# Idempotent: re-running is safe.
set -euo pipefail

ok() { printf '    \033[0;32m✓\033[0m %s\n' "$*"; }

export DEBIAN_FRONTEND=noninteractive

# ─── Packages ───────────────────────────────────────────────────────
# No nginx, no fail2ban-for-a-public-service — there is nothing listening
# for fail2ban to protect. unattended-upgrades and the Docker/Tailscale
# pieces are identical to the gateway's needs.
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq unattended-upgrades curl gnupg
ok "packages installed"

# ─── Docker ─────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker >/dev/null 2>&1
  ok "docker installed"
else
  ok "docker already installed"
fi

# ─── Tailscale ──────────────────────────────────────────────────────
# Identical reasoning and procedure to bootstrap.sh's Tailscale section —
# see that file and production-runbook.md's Tailscale writeup for the
# full "why". The one difference: this VM never had a standing port-22
# NSG rule to begin with (provision-worker.sh creates it with
# --nsg-rule NONE and adds nothing after), so there is no rule to delete
# once Tailscale is confirmed working — just confirm `ssh
# azureuser@<tailscale-ip>` works and move on.
if ! command -v tailscale >/dev/null 2>&1; then
  curl -fsSL https://tailscale.com/install.sh | sh
  ok "tailscale installed"
else
  ok "tailscale already installed"
fi
if ! tailscale status >/dev/null 2>&1; then
  echo
  echo "    ACTION REQUIRED — this VM is not on the tailnet yet."
  echo "    Generate a reusable auth key: Tailscale admin console → Settings"
  echo "    → Keys → Generate auth key. Then, from your own machine (not"
  echo "    over SSH to this VM, since that's the access this restores):"
  echo "        az vm run-command invoke -g foundry-rg -n foundry-worker \\"
  echo "          --command-id RunShellScript \\"
  echo "          --scripts \"tailscale up --authkey=<the key> --hostname=foundry-worker\""
  echo "    Confirm \`ssh azureuser@<100.x.x.x>\` works before relying on it —"
  echo "    this VM has no port-22 NSG rule at all, so Tailscale is the ONLY"
  echo "    way in short of the Azure Serial Console."
  echo
else
  ok "already joined to the tailnet"
fi

cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
EOF
systemctl enable --now unattended-upgrades >/dev/null 2>&1 || true
ok "unattended-upgrades enabled"

# ─── Secrets ────────────────────────────────────────────────────────
# No dedicated `foundry` service user, same reasoning as the gateway: the
# worker container runs as the non-root `gateway` user baked into the
# shared image (server/Dockerfile), sandboxed by Docker rather than a
# host account. systemd runs `docker` as root, same tradeoff as
# foundry-worker@.service already documents.
#
# worker.env, not gateway.env — confirmed against server/app/worker.py
# and app/config.py's WorkerSettings. No AZURE_* *credential* lives here —
# this VM reads blobs via the managed identity DefaultAzureCredential
# resolves automatically (provision-worker.sh's RBAC grant), never via a
# stored credential. It DOES need two non-secret Azure *identifiers*
# though (storage.py's _service() and process_ingest_cv() both need to
# know which account/container to point the SDK at, regardless of how
# the SDK authenticates) — AZURE_STORAGE_ACCOUNT and AZURE_CV_CONTAINER,
# baked in below with real values since they're fixed, non-secret,
# already-known identifiers (production-runbook.md), not per-deploy
# secrets a human needs to generate.
#
# Generated here, once, and never regenerated by a re-run — same
# discipline as gateway.env, for the same reason (rotating DATABASE_URL
# silently would desync every running worker instance until restarted).
mkdir -p /etc/foundry
if [ ! -f /etc/foundry/worker.env ]; then
  cat > /etc/foundry/worker.env <<EOF
AZURE_STORAGE_ACCOUNT=foundryqua2o4gw1s13
AZURE_CV_CONTAINER=member-cvs
DATABASE_URL=CHANGE_ME
OPENAI_API_KEY=CHANGE_ME
GITHUB_TOKEN_ENCRYPTION_KEY=CHANGE_ME
EOF
  chmod 600 /etc/foundry/worker.env
  ok "generated /etc/foundry/worker.env (placeholder values)"
  echo
  echo "    ACTION REQUIRED — fill in the three values above by hand:"
  echo "        sudo nano /etc/foundry/worker.env"
  echo "    DATABASE_URL: the Supabase session-pooler connection string"
  echo "      (server/README.md — NOT the direct connection, which is"
  echo "      IPv6-only and this VM has no IPv6)."
  echo "    OPENAI_API_KEY / GITHUB_TOKEN_ENCRYPTION_KEY: from wherever"
  echo "      these are currently held for local/CI use — never rotate"
  echo "      GITHUB_TOKEN_ENCRYPTION_KEY without a migration plan, it"
  echo "      would make every stored GitHub token undecryptable."
  echo
else
  ok "/etc/foundry/worker.env already exists — left alone"
fi

# ─── GHCR pull credential ───────────────────────────────────────────
# Identical to the gateway's — same private image, same registry, same
# "a human makes this, no API can" reasoning.
if [ ! -f /etc/foundry/ghcr-pull.env ]; then
  echo
  echo "    ACTION REQUIRED — GHCR pull credential not installed."
  echo "    github.com/settings/tokens → Generate new token (classic) →"
  echo "    scope: read:packages only. Then:"
  echo "        sudo tee /etc/foundry/ghcr-pull.env <<EOF"
  echo "        GHCR_USERNAME=<your github username>"
  echo "        GHCR_TOKEN=<the token>"
  echo "        EOF"
  echo "        sudo chmod 600 /etc/foundry/ghcr-pull.env"
  echo "    No worker instance will start until this exists — its image is"
  echo "    private and docker pull needs to authenticate."
  echo
else
  chmod 600 /etc/foundry/ghcr-pull.env
  ok "/etc/foundry/ghcr-pull.env already exists — left alone"
fi

# ─── SSH hardening ──────────────────────────────────────────────────
cat > /etc/ssh/sshd_config.d/10-foundry.conf <<'EOF'
PasswordAuthentication no
PermitRootLogin no
KbdInteractiveAuthentication no
EOF
if sshd -t 2>/dev/null; then
  systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || true
  ok "SSH: keys only, no root login"
else
  echo "    ! sshd config invalid — removing the drop-in rather than locking you out" >&2
  rm -f /etc/ssh/sshd_config.d/10-foundry.conf
fi

ok "bootstrap complete — instances are NOT auto-enabled; run"
echo "        systemctl enable --now foundry-worker@1"
echo "    once worker.env holds real values and the B2.8 load test has"
echo "    said how many instances to run."
